name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          # Si vous avez un requirements.txt, faites plutôt :
          # pip install -r requirements.txt
          # pip install pylint

      - name: Run pylint
        run: |
          # Analyse de tous les fichiers .py
          pylint $(find . -type f -name "*.py")
          # Ou plus simplement :
          # pylint .
