name: PyTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installez ici vos dépendances :
          # pip install -r requirements.txt
          # Pour cet exemple, on installe seulement pytest :
          pip install pytest

      - name: Run tests
        run: |
          # Lancez pytest depuis la racine (ou spécifiez un répertoire si nécessaire)
          pytest
